# Generated by Django 5.1.4 on 2024-12-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_users_income_budget_expense_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.users'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.users'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.users'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_app.users'),
        ),
    ]
