# Generated by Django 5.1.4 on 2024-12-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_update_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='set_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_app.update_goal'),
        ),
    ]
