# Generated by Django 5.1.4 on 2024-12-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_goal_set_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='set_amount',
            field=models.IntegerField(null=True),
        ),
    ]
