# Generated by Django 5.0.3 on 2025-01-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0008_alter_expert_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
